# Generated by Django 5.0 on 2024-03-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_rename_profiles_profile_candidacyandvot_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='election_candidacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='no_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='voted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CandidacyAndVot',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
