# Generated by Django 5.0 on 2024-04-06 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_electionround_electionranking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionranking',
            old_name='candidate_name',
            new_name='candidate',
        ),
        migrations.AlterUniqueTogether(
            name='electionranking',
            unique_together={('election_round', 'candidate')},
        ),
        migrations.RemoveField(
            model_name='electionround',
            name='finalized',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='election_candidacy',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='no_votes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='voted',
        ),
        migrations.AddField(
            model_name='electionranking',
            name='no_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electionround',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='electionranking',
            name='rank',
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=100)),
                ('election_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.electionround')),
                ('user_votes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_votes', 'election_round')},
            },
        ),
    ]
